import Button from "./_components/Button"
import './styles.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Button/>
      {children}</body>
    </html>
  )
}
