// Navigation data structure
export const navbarData = {
    main: [
        { id: "design", label: "Design Spotlight" },
        { id: "business", label: "Business" },
        { id: "education", label: "Education" },
        { id: "plans", label: "Plans and Pricing" },
        { id: "learn", label: "Learn" },
    ],
    design: [
        {
            id: "design1",
            type: "headline",
            label: "Visual Documents",
            link: "#",
            navItems: [
                { id: "design2", label: "Visual Suite", link: "#" },
                { id: "design3", label: "Docs", link: "#" },
                { id: "design4", label: "Presentations", link: "#" },
                { id: "design5", label: "Whiteboards", link: "#" },
                { id: "design6", label: "PDF Editor", link: "#" },
                { id: "design7", label: "Graphs and Charts", link: "#" },
                { id: "design8", label: "Sheets", link: "#" },
                { id: "design9", label: "Canva AI", link: "#" },
            ],
        },
        {
            id: "design10",
            type: "headline",
            label: "Photos and Videos",
            link: "#",
            navItems: [
                { id: "design11", label: "Video Editor", link: "#" },
                { id: "design12", label: "YouTube Video Editor", link: "#" },
                { id: "design13", label: "Photo Editor", link: "#" },
                { id: "design14", label: "Photo Collages", link: "#" },
                { id: "design15", label: "Background Remover", link: "#" },
            ],
        },
        {
            id: "design16",
            type: "headline",
            label: "Print",
            link: "#",
            navItems: [
                { id: "design17", label: "Business Cards", link: "#" },
                { id: "design18", label: "Cards", link: "#" },
                { id: "design19", label: "Invitations", link: "#" },
                { id: "design20", label: "Mugs", link: "#" },
                { id: "design21", label: "T-Shirts", link: "#" },
                { id: "design22", label: "Hoodies", link: "#" },
                { id: "design23", label: "Calendars", link: "#" },
                { id: "design24", label: "Labels", link: "#" },
                { id: "design25", label: "See all", link: "#" },
            ],
        },
        {
            id: "design26",
            type: "headline",
            label: "Marketing",
            link: "#",
            navItems: [
                { id: "design27", label: "Logos", link: "#" },
                { id: "design28", label: "Posters", link: "#" },
                { id: "design29", label: "Flyers", link: "#" },
                { id: "design30", label: "Brochures", link: "#" },
                { id: "design31", label: "Social Media", link: "#" },
                { id: "design32", label: "Websites", link: "#" },
                { id: "design33", label: "Stickers", link: "#" },
                { id: "design34", label: "Mockups", link: "#" },
                { id: "design35", label: "QR Code Generator", link: "#" },
                { id: "design36", label: "Browse Canva Templates", link: "#" },
                { id: "design37", label: "Magic Studio", link: "#" },
            ],
        },
    ],
    business: [
        {
            id: "business1",
            type: "headline",
            label: "Business Solutions",
            link: "#",
            navItems: [
                { id: "business2", label: "Marketing", link: "#" },
                { id: "business3", label: "Creatives", link: "#" },
                { id: "business4", label: "Agencies", link: "#" },
                { id: "business5", label: "Sales", link: "#" },
                { id: "business6", label: "Communications", link: "#" },
                { id: "business7", label: "Real Estate", link: "#" },
                { id: "business8", label: "Small and Medium Business", link: "#" },
                { id: "business9", label: "Startups", link: "#" },
                { id: "business27", label: "Franchises", link: "#" },
            ],
        },
        {
            id: "business10",
            type: "headline",
            label: "Use Case",
            link: "#",
            navItems: [
                { id: "business11", label: "Content Creation", link: "#" },
                { id: "business12", label: "Visual Communication", link: "#" },
                { id: "business13", label: "Brand Management", link: "#" },
                { id: "business14", label: "Team Collaboration", link: "#" },
                { id: "business15", label: "Asset Management", link: "#" },
                { id: "business24", label: "Brainstorms and Workshops", link: "#" },
                { id: "business25", label: "Branded Team Templates", link: "#" },
                { id: "business26", label: "Productivity and Workflows", link: "#" },
            ],
        },
        {
            id: "business16",
            type: "headline",
            label: "Resources",
            link: "#",
            navItems: [
                { id: "business17", label: "Business Resources", link: "#" },
                { id: "business18", label: "Case Studies", link: "#" },
                { id: "business19", label: "Features", link: "#" },
                { id: "business20", label: "Integrations and Apps", link: "#" },
                { id: "business21", label: "Security", link: "#" },
                { id: "business22", label: "Enterprise Onboarding Services", link: "#" },
                { id: "business23", label: "ROI Calculator", link: "#" },
            ],
        },
    ],
    education: [
        {
            id: "design1",
            type: "headline",
            label: "Business Solutions",
            link: "#",
            navItems: [
                { id: "design2", label: "Visual Suite", link: "#" },
                { id: "design3", label: "Docs", link: "#" },
                { id: "design4", label: "Presentations", link: "#" },
                { id: "design5", label: "Whiteboards", link: "#" },
                { id: "design6", label: "PDF Editor", link: "#" },
                { id: "design7", label: "Graphs and Charts", link: "#" },
                { id: "design8", label: "Sheets", link: "#" },
                { id: "design9", label: "Canva AI", link: "#" },
            ],
        },
        {
            id: "design10",
            type: "headline",
            label: "Photos and Videos",
            link: "#",
            navItems: [
                { id: "design11", label: "Video Editor", link: "#" },
                { id: "design12", label: "YouTube Video Editor", link: "#" },
                { id: "design13", label: "Photo Editor", link: "#" },
                { id: "design14", label: "Photo Collages", link: "#" },
                { id: "design15", label: "Background Remover", link: "#" },
            ],
        },
        {
            id: "design16",
            type: "headline",
            label: "Print",
            link: "#",
            navItems: [
                { id: "design17", label: "Business Cards", link: "#" },
                { id: "design18", label: "Cards", link: "#" },
                { id: "design19", label: "Invitations", link: "#" },
                { id: "design20", label: "Mugs", link: "#" },
                { id: "design21", label: "T-Shirts", link: "#" },
                { id: "design22", label: "Hoodies", link: "#" },
                { id: "design23", label: "Calendars", link: "#" },
                { id: "design24", label: "Labels", link: "#" },
                { id: "design25", label: "See all", link: "#" },
            ],
        },
        {
            id: "design26",
            type: "headline",
            label: "Marketing",
            link: "#",
            navItems: [
                { id: "design27", label: "Logos", link: "#" },
                { id: "design28", label: "Posters", link: "#" },
                { id: "design29", label: "Flyers", link: "#" },
                { id: "design30", label: "Brochures", link: "#" },
                { id: "design31", label: "Social Media", link: "#" },
                { id: "design32", label: "Websites", link: "#" },
                { id: "design33", label: "Stickers", link: "#" },
                { id: "design34", label: "Mockups", link: "#" },
                { id: "design35", label: "QR Code Generator", link: "#" },
                { id: "design36", label: "Browse Canva Templates", link: "#" },
                { id: "design37", label: "Magic Studio", link: "#" },
            ],
        },
    ],
    plans: [
        {
            id: "design1",
            type: "headline",
            label: "Visual Documents",
            link: "#",
            navItems: [
                { id: "design2", label: "Visual Suite", link: "#" },
                { id: "design3", label: "Docs", link: "#" },
                { id: "design4", label: "Presentations", link: "#" },
                { id: "design5", label: "Whiteboards", link: "#" },
                { id: "design6", label: "PDF Editor", link: "#" },
                { id: "design7", label: "Graphs and Charts", link: "#" },
                { id: "design8", label: "Sheets", link: "#" },
                { id: "design9", label: "Canva AI", link: "#" },
            ],
        },
        {
            id: "design10",
            type: "headline",
            label: "Photos and Videos",
            link: "#",
            navItems: [
                { id: "design11", label: "Video Editor", link: "#" },
                { id: "design12", label: "YouTube Video Editor", link: "#" },
                { id: "design13", label: "Photo Editor", link: "#" },
                { id: "design14", label: "Photo Collages", link: "#" },
                { id: "design15", label: "Background Remover", link: "#" },
            ],
        },
        {
            id: "design16",
            type: "headline",
            label: "Print",
            link: "#",
            navItems: [
                { id: "design17", label: "Business Cards", link: "#" },
                { id: "design18", label: "Cards", link: "#" },
                { id: "design19", label: "Invitations", link: "#" },
                { id: "design20", label: "Mugs", link: "#" },
                { id: "design21", label: "T-Shirts", link: "#" },
                { id: "design22", label: "Hoodies", link: "#" },
                { id: "design23", label: "Calendars", link: "#" },
                { id: "design24", label: "Labels", link: "#" },
                { id: "design25", label: "See all", link: "#" },
            ],
        },
        {
            id: "design26",
            type: "headline",
            label: "Marketing",
            link: "#",
            navItems: [
                { id: "design27", label: "Logos", link: "#" },
                { id: "design28", label: "Posters", link: "#" },
                { id: "design29", label: "Flyers", link: "#" },
                { id: "design30", label: "Brochures", link: "#" },
                { id: "design31", label: "Social Media", link: "#" },
                { id: "design32", label: "Websites", link: "#" },
                { id: "design33", label: "Stickers", link: "#" },
                { id: "design34", label: "Mockups", link: "#" },
                { id: "design35", label: "QR Code Generator", link: "#" },
                { id: "design36", label: "Browse Canva Templates", link: "#" },
                { id: "design37", label: "Magic Studio", link: "#" },
            ],
        },
    ],
    learn: [
        {
            id: "design1",
            type: "headline",
            label: "Visual Documents",
            link: "#",
            navItems: [
                { id: "design2", label: "Visual Suite", link: "#" },
                { id: "design3", label: "Docs", link: "#" },
                { id: "design4", label: "Presentations", link: "#" },
                { id: "design5", label: "Whiteboards", link: "#" },
                { id: "design6", label: "PDF Editor", link: "#" },
                { id: "design7", label: "Graphs and Charts", link: "#" },
                { id: "design8", label: "Sheets", link: "#" },
                { id: "design9", label: "Canva AI", link: "#" },
            ],
        },
        {
            id: "design10",
            type: "headline",
            label: "Photos and Videos",
            link: "#",
            navItems: [
                { id: "design11", label: "Video Editor", link: "#" },
                { id: "design12", label: "YouTube Video Editor", link: "#" },
                { id: "design13", label: "Photo Editor", link: "#" },
                { id: "design14", label: "Photo Collages", link: "#" },
                { id: "design15", label: "Background Remover", link: "#" },
            ],
        },
        {
            id: "design16",
            type: "headline",
            label: "Print",
            link: "#",
            navItems: [
                { id: "design17", label: "Business Cards", link: "#" },
                { id: "design18", label: "Cards", link: "#" },
                { id: "design19", label: "Invitations", link: "#" },
                { id: "design20", label: "Mugs", link: "#" },
                { id: "design21", label: "T-Shirts", link: "#" },
                { id: "design22", label: "Hoodies", link: "#" },
                { id: "design23", label: "Calendars", link: "#" },
                { id: "design24", label: "Labels", link: "#" },
                { id: "design25", label: "See all", link: "#" },
            ],
        },
        {
            id: "design26",
            type: "headline",
            label: "Marketing",
            link: "#",
            navItems: [
                { id: "design27", label: "Logos", link: "#" },
                { id: "design28", label: "Posters", link: "#" },
                { id: "design29", label: "Flyers", link: "#" },
                { id: "design30", label: "Brochures", link: "#" },
                { id: "design31", label: "Social Media", link: "#" },
                { id: "design32", label: "Websites", link: "#" },
                { id: "design33", label: "Stickers", link: "#" },
                { id: "design34", label: "Mockups", link: "#" },
                { id: "design35", label: "QR Code Generator", link: "#" },
                { id: "design36", label: "Browse Canva Templates", link: "#" },
                { id: "design37", label: "Magic Studio", link: "#" },
            ],
        },
    ],
};
